import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { Calendar, User, ArrowLeft, Eye, Share2, Bookmark, Printer, Facebook, Twitter, Linkedin, ArrowRight } from 'lucide-react';
import Button from '../components/ui/Button';

const BlogPost = () => {
  const { id } = useParams<{ id: string }>();
  
  // In a real application, you would fetch the blog post data based on the ID
  // For now, we'll use mock data
  const post = {
    id: parseInt(id || '1'),
    title: "The Complete Guide to Forex Trading in 2024",
    excerpt: "Everything you need to know about forex trading, from basics to advanced strategies. Learn how to navigate the world's largest financial market.",
    content: `
      <h2>Introduction to Forex Trading</h2>
      <p>The foreign exchange market (Forex, FX, or currency market) is a global decentralized or over-the-counter (OTC) market for the trading of currencies. This market determines foreign exchange rates for every currency. It includes all aspects of buying, selling and exchanging currencies at current or determined prices.</p>
      
      <p>In terms of trading volume, it is by far the largest market in the world, followed by the credit market. The main participants in this market are the larger international banks. Financial centers around the world function as anchors of trading between a wide range of multiple types of buyers and sellers around the clock, with the exception of weekends.</p>
      
      <h2>Understanding Currency Pairs</h2>
      <p>Currencies are always traded in pairs. When you trade in the forex market, you buy or sell in currency pairs. The exchange rate is the price of one currency expressed in terms of another currency.</p>
      
      <p>For example, the EUR/USD exchange rate tells the trader how many US dollars (USD) it takes to buy one euro (EUR). The first currency listed (EUR) is the base currency and the second (USD) is the quote or counter currency.</p>
      
      <h2>Major Currency Pairs</h2>
      <p>The four major currency pairs are:</p>
      <ul>
        <li>EUR/USD (Euro/US Dollar) - The most traded currency pair in the world</li>
        <li>USD/JPY (US Dollar/Japanese Yen) - The second most traded pair</li>
        <li>GBP/USD (British Pound/US Dollar) - Also known as "Cable"</li>
        <li>USD/CHF (US Dollar/Swiss Franc) - Considered a safe-haven currency pair</li>
      </ul>
      
      <h2>Market Analysis Techniques</h2>
      <p>There are two main types of analysis used to forecast the behavior of the Forex market:</p>
      
      <h3>Fundamental Analysis</h3>
      <p>Fundamental analysis is a method of evaluating a currency by measuring the economic, social, and political forces that may affect the supply and demand of an asset. Fundamental analysts focus on economic indicators, such as:</p>
      <ul>
        <li>Interest rates</li>
        <li>Employment rates</li>
        <li>GDP (Gross Domestic Product)</li>
        <li>International trade</li>
        <li>Manufacturing</li>
        <li>Geopolitical events</li>
      </ul>
      
      <h3>Technical Analysis</h3>
      <p>Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. Technical analysts do not attempt to measure a security's intrinsic value, but instead use charts and other tools to identify patterns that can suggest future activity.</p>
      
      <p>Common technical indicators include:</p>
      <ul>
        <li>Moving Averages</li>
        <li>Relative Strength Index (RSI)</li>
        <li>Moving Average Convergence Divergence (MACD)</li>
        <li>Bollinger Bands</li>
        <li>Fibonacci Retracement</li>
      </ul>
      
      <h2>Risk Management in Forex Trading</h2>
      <p>Risk management is perhaps the most important aspect of trading success. Here are some key principles:</p>
      
      <h3>The 2% Rule</h3>
      <p>Never risk more than 2% of your account on a single trade. This helps ensure that a string of losses won't significantly deplete your trading capital.</p>
      
      <h3>Position Sizing</h3>
      <p>Calculate your position size based on your account size, risk percentage, and the distance to your stop loss. This ensures consistent risk across different trades.</p>
      
      <h3>Stop Loss Orders</h3>
      <p>Always use stop loss orders to limit potential losses. A stop loss is an order placed with a broker to sell a security when it reaches a certain price, limiting potential losses.</p>
      
      <h3>Risk-Reward Ratio</h3>
      <p>Aim for a risk-reward ratio of at least 1:2, meaning your potential profit should be at least twice your potential loss. This allows you to be profitable even if you lose more trades than you win.</p>
      
      <h2>Developing a Trading Plan</h2>
      <p>A comprehensive trading plan should include:</p>
      <ul>
        <li>Trading goals (both short-term and long-term)</li>
        <li>Risk management rules</li>
        <li>Entry and exit criteria</li>
        <li>Markets and timeframes to trade</li>
        <li>Position sizing formula</li>
        <li>Trading hours</li>
        <li>Record-keeping procedures</li>
      </ul>
      
      <h2>Conclusion</h2>
      <p>Forex trading offers significant opportunities but also comes with substantial risks. Success in this market requires education, practice, discipline, and effective risk management. By understanding the basics outlined in this guide and continuing to develop your knowledge and skills, you can work toward becoming a successful forex trader.</p>
      
      <p>Remember that consistent profitability takes time and experience. Many successful traders recommend starting with a demo account to practice without risking real money, then transitioning to small position sizes when moving to a live account.</p>
    `,
    author: "Gary Robinson",
    date: "2024-06-24",
    category: "Forex Trading",
    readTime: "12 min read",
    image: "https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    views: 2847,
    relatedPosts: [
      {
        id: 3,
        title: "5 Risk Management Rules Every Trader Must Follow",
        category: "Trading Psychology",
        image: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
      },
      {
        id: 5,
        title: "EUR/USD Weekly Outlook: Key Levels to Watch",
        category: "Market Analysis",
        image: "https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
      },
      {
        id: 8,
        title: "S&P 500 Futures: Trading the Index Like a Pro",
        category: "Futures",
        image: "https://images.pexels.com/photos/8370752/pexels-photo-8370752.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
      }
    ]
  };

  return (
    <div className="pt-24">
      {/* SEO Meta Tags */}
      <title>{post.title} - Gary Robinson Trading</title>
      <meta name="description" content={post.excerpt} />
      
      {/* Hero Section */}
      <section className="py-16 md:py-24 bg-gradient-to-br from-blue-900 via-blue-800 to-blue-700 text-white">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-4xl mx-auto">
            <Link to="/blog" className="inline-flex items-center text-gray-200 hover:text-yellow-500 transition-colors mb-6">
              <ArrowLeft className="mr-2" size={16} />
              Back to Blog
            </Link>
            
            <h1 className="text-3xl md:text-5xl font-bold mb-6">
              {post.title}
            </h1>
            
            <div className="flex flex-wrap items-center text-sm text-gray-200 mb-8">
              <div className="flex items-center mr-6 mb-2">
                <User className="mr-2" size={16} />
                {post.author}
              </div>
              <div className="flex items-center mr-6 mb-2">
                <Calendar className="mr-2" size={16} />
                {new Date(post.date).toLocaleDateString()}
              </div>
              <div className="flex items-center mr-6 mb-2">
                <Eye className="mr-2" size={16} />
                {post.views} views
              </div>
              <div className="px-3 py-1 bg-blue-800 rounded-full mb-2">
                {post.category}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Article Content */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
            {/* Main Content */}
            <div className="lg:col-span-8">
              <div className="bg-white rounded-2xl shadow-lg overflow-hidden">
                <img 
                  src={post.image} 
                  alt={post.title} 
                  className="w-full h-80 object-cover"
                />
                
                <div className="p-8">
                  <div className="prose prose-lg max-w-none">
                    <div dangerouslySetInnerHTML={{ __html: post.content }}></div>
                  </div>
                  
                  {/* Tags */}
                  <div className="mt-8 pt-8 border-t border-gray-200">
                    <h4 className="font-bold text-gray-700 mb-3">Tags</h4>
                    <div className="flex flex-wrap gap-2">
                      <span className="bg-gray-100 text-gray-800 px-3 py-1 rounded-full text-sm">Forex</span>
                      <span className="bg-gray-100 text-gray-800 px-3 py-1 rounded-full text-sm">Trading</span>
                      <span className="bg-gray-100 text-gray-800 px-3 py-1 rounded-full text-sm">Technical Analysis</span>
                      <span className="bg-gray-100 text-gray-800 px-3 py-1 rounded-full text-sm">Risk Management</span>
                      <span className="bg-gray-100 text-gray-800 px-3 py-1 rounded-full text-sm">Currency Pairs</span>
                    </div>
                  </div>
                  
                  {/* Share */}
                  <div className="mt-8 pt-8 border-t border-gray-200">
                    <h4 className="font-bold text-gray-700 mb-3">Share This Article</h4>
                    <div className="flex gap-3">
                      <button className="p-2 bg-blue-600 text-white rounded-full hover:bg-blue-700 transition-colors">
                        <Facebook size={18} />
                      </button>
                      <button className="p-2 bg-blue-400 text-white rounded-full hover:bg-blue-500 transition-colors">
                        <Twitter size={18} />
                      </button>
                      <button className="p-2 bg-blue-700 text-white rounded-full hover:bg-blue-800 transition-colors">
                        <Linkedin size={18} />
                      </button>
                      <button className="p-2 bg-gray-200 text-gray-700 rounded-full hover:bg-gray-300 transition-colors">
                        <Printer size={18} />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            {/* Sidebar */}
            <div className="lg:col-span-4">
              {/* Author Bio */}
              <div className="bg-gray-50 rounded-2xl p-6 shadow-md mb-8">
                <div className="flex items-center mb-4">
                  <img 
                    src="https://images.pexels.com/photos/7821906/pexels-photo-7821906.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" 
                    alt="Gary Robinson" 
                    className="w-16 h-16 rounded-full object-cover mr-4"
                  />
                  <div>
                    <h3 className="font-bold text-blue-900">{post.author}</h3>
                    <p className="text-gray-600 text-sm">Professional Trader & Educator</p>
                  </div>
                </div>
                <p className="text-gray-700 text-sm">
                  Gary Robinson is a professional trader with over 10 years of experience in Forex, Futures, and Cryptocurrency markets. He has trained over 2,500 students worldwide.
                </p>
                <div className="mt-4">
                  <Link to="/about">
                    <Button variant="outline" size="sm" fullWidth>
                      View Profile
                    </Button>
                  </Link>
                </div>
              </div>
              
              {/* Related Posts */}
              <div className="bg-gray-50 rounded-2xl p-6 shadow-md mb-8">
                <h3 className="font-bold text-blue-900 mb-4">Related Articles</h3>
                <div className="space-y-4">
                  {post.relatedPosts.map((relatedPost) => (
                    <Link key={relatedPost.id} to={`/blog/${relatedPost.id}`} className="flex items-start group">
                      <img 
                        src={relatedPost.image} 
                        alt={relatedPost.title} 
                        className="w-16 h-16 object-cover rounded-lg mr-3"
                      />
                      <div>
                        <h4 className="font-medium text-gray-800 group-hover:text-blue-700 transition-colors line-clamp-2">
                          {relatedPost.title}
                        </h4>
                        <p className="text-xs text-gray-600 mt-1">{relatedPost.category}</p>
                      </div>
                    </Link>
                  ))}
                </div>
              </div>
              
              {/* Save for Later */}
              <div className="bg-blue-50 rounded-2xl p-6 shadow-md mb-8">
                <div className="flex items-center mb-4">
                  <Bookmark className="text-blue-900 mr-2" size={20} />
                  <h3 className="font-bold text-blue-900">Save for Later</h3>
                </div>
                <p className="text-gray-700 text-sm mb-4">
                  Want to read this article later? Download a PDF version to read offline.
                </p>
                <Button variant="primary" size="sm" fullWidth>
                  Download PDF
                </Button>
              </div>
              
              {/* Newsletter */}
              <div className="bg-gradient-to-br from-blue-900 to-blue-800 rounded-2xl p-6 shadow-md text-white">
                <h3 className="font-bold mb-3">Get Trading Insights</h3>
                <p className="text-gray-200 text-sm mb-4">
                  Subscribe to our newsletter for weekly trading analysis and tips.
                </p>
                <input 
                  type="email" 
                  placeholder="Your email address" 
                  className="w-full px-3 py-2 rounded-lg text-gray-900 mb-3 focus:outline-none focus:ring-2 focus:ring-yellow-500"
                />
                <Button variant="secondary" size="sm" fullWidth>
                  Subscribe
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* More Articles */}
      <section className="py-16 bg-gray-50">
        <div className="container mx-auto px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-blue-900 mb-4">
              More Articles You Might Like
            </h2>
            <div className="w-20 h-1 bg-yellow-500 mx-auto mb-6"></div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {post.relatedPosts.map((relatedPost) => (
              <article key={relatedPost.id} className="bg-white rounded-2xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300">
                <div className="relative h-48 overflow-hidden">
                  <img 
                    src={relatedPost.image} 
                    alt={relatedPost.title} 
                    className="w-full h-full object-cover hover:scale-105 transition-transform duration-300"
                  />
                  <div className="absolute top-4 left-4">
                    <span className="bg-blue-900 text-white px-3 py-1 rounded-full text-xs font-medium">
                      {relatedPost.category}
                    </span>
                  </div>
                </div>
                
                <div className="p-6">
                  <h3 className="font-bold text-blue-900 mb-4 line-clamp-2">
                    <Link to={`/blog/${relatedPost.id}`} className="hover:text-blue-700 transition-colors">
                      {relatedPost.title}
                    </Link>
                  </h3>
                  
                  <Link to={`/blog/${relatedPost.id}`} className="flex items-center text-blue-900 font-medium hover:text-blue-700 transition-colors">
                    Read Article
                    <ArrowRight className="ml-1" size={16} />
                  </Link>
                </div>
              </article>
            ))}
          </div>
          
          <div className="text-center mt-12">
            <Link to="/blog">
              <Button variant="outline" size="lg">
                View All Articles
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
};

export default BlogPost;